Toggle enterprise feature
confluent-helm-charts/cp-helm-charts pull request #1
Opened 2021-11-30 14:18 UTC by redsk

## What changes were proposed in this pull request?

Add a variable to cp-kafka/values.yaml to enable or disable enterprise
features. Same as https://github.com/confluentinc/cp-helm-charts/pull/436 .

Fixes #377

This PR is completely based on the work of @oscarh on #378 with just a small change to fulfill the request to disable the control center when enableEnterpriseFeatures=false: I simply flipped the order of

condition: cp-kafka.enableEnterpriseFeatures, cp-control-center.enabled

## How was this patch tested?

```
helm template --set cp-kafka.enableEnterpriseFeatures=false . > ~/tmp/kafka_enterprise_disabled.yaml
helm template --set cp-kafka.enableEnterpriseFeatures=true . > ~/tmp/kafka_enterprise_enabled.yaml
diff -u ~/tmp/kafka_enterprise_{enabled,disabled}.yaml
```
```
--- /Users/niki/tmp/kafka_enterprise_enabled.yaml	2021-11-30 15:16:56.000000000 +0100
+++ /Users/niki/tmp/kafka_enterprise_disabled.yaml	2021-11-30 15:16:56.000000000 +0100
@@ -241,24 +241,6 @@
         replicaId: "$2"
         memberType: "$3"
 ---
-# Source: cp-helm-charts/charts/cp-control-center/templates/service.yaml
-apiVersion: v1
-kind: Service
-metadata:
-  name: RELEASE-NAME-cp-control-center
-  labels:
-    app: cp-control-center
-    chart: cp-control-center-0.1.0
-    release: RELEASE-NAME
-    heritage: Helm
-spec:
-  ports:
-    - name: cc-http
-      port: 9021
-  selector:
-    app: cp-control-center
-    release: RELEASE-NAME
----
 # Source: cp-helm-charts/charts/cp-kafka-connect/templates/service.yaml
 apiVersion: v1
 kind: Service
@@ -420,59 +402,6 @@
     app: cp-zookeeper
     release: RELEASE-NAME
 ---
-# Source: cp-helm-charts/charts/cp-control-center/templates/deployment.yaml
-apiVersion: apps/v1
-kind: Deployment
-metadata:
-  name: RELEASE-NAME-cp-control-center
-  labels:
-    app: cp-control-center
-    chart: cp-control-center-0.1.0
-    release: RELEASE-NAME
-    heritage: Helm
-spec:
-  replicas: 1
-  selector:
-    matchLabels:
-      app: cp-control-center
-      release: RELEASE-NAME
-  template:
-    metadata:
-      labels:
-        app: cp-control-center
-        release: RELEASE-NAME
-      annotations:
-        prometheus.io/scrape: "true"
-        prometheus.io/port: "5556"
-    spec:
-      containers:
-        - name: cp-control-center
-          image: "confluentinc/cp-enterprise-control-center:6.1.0"
-          imagePullPolicy: IfNotPresent
-          ports:
-            - name: cc-http
-              containerPort: 9021
-              protocol: TCP
-          resources:
-            {}
-          env:
-            - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
-              value: PLAINTEXT://RELEASE-NAME-cp-kafka-headless:9092
-            - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
-              value:
-            - name: CONTROL_CENTER_CONNECT_CLUSTER
-              value: http://RELEASE-NAME-cp-kafka-connect:8083
-            - name: CONTROL_CENTER_KSQL_URL
-              value: http://RELEASE-NAME-cp-ksql-server:8088
-            - name: CONTROL_CENTER_KSQL_ADVERTISED_URL
-              value: http://RELEASE-NAME-cp-ksql-server:8088
-            - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
-              value: http://RELEASE-NAME-cp-schema-registry:8081
-            - name: KAFKA_HEAP_OPTS
-              value: "-Xms512M -Xmx512M"
-            - name: "CONTROL_CENTER_REPLICATION_FACTOR"
-              value: "3"
----
 # Source: cp-helm-charts/charts/cp-kafka-connect/templates/deployment.yaml
 apiVersion: apps/v1
 kind: Deployment
@@ -881,7 +810,7 @@
         - name: jmx-config
           mountPath: /etc/jmx-kafka
       - name: cp-kafka-broker
-        image: "confluentinc/cp-enterprise-kafka:6.1.0"
+        image: "confluentinc/cp-kafka:6.1.0"
         imagePullPolicy: "IfNotPresent"
         securityContext:
           runAsUser: 0
@@ -915,10 +844,6 @@
           value: "RELEASE-NAME-cp-zookeeper-headless:2181"
         - name: KAFKA_LOG_DIRS
           value: "/opt/kafka/data-0/logs"
-        - name: KAFKA_METRIC_REPORTERS
-          value: "io.confluent.metrics.reporter.ConfluentMetricsReporter"
-        - name: CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS
-          value: "PLAINTEXT://RELEASE-NAME-cp-kafka-headless:9092"
         - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
           value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
         - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
```

2021-12-02 12:18 UTC, redsk commented
@gAmUssA

2021-12-07 03:12 UTC, gAmUssA requested changes

2021-12-07 03:12 UTC, gAmUssA commented on charts/cp-kafka/templates/statefulset.yaml
> +        image: "confluentinc/cp-enterprise-kafka:{{ .Values.imageTag }}"
cp-enterprise-kafka images are deprecated. use cp-server https://hub.docker.com/r/confluentinc/cp-server

2021-12-07 03:12 UTC, gAmUssA commented on values.yaml
> +  # image: confluentinc/cp-enterprise-kafka
use cp-server instead https://hub.docker.com/r/confluentinc/cp-server

2021-12-13 20:47 UTC, redsk commented
@gAmUssA changes made as requested

2021-12-14 16:51 UTC, gAmUssA commented
kindly rebase, @redsk 
PR LGTM

2021-12-14 19:58 UTC, redsk commented
@gAmUssA rebased. Also changed two existing occurrences of `cp-enterprise-kafka`

2021-12-18 12:30 UTC, redsk commented
@gAmUssA do you think this pr is ready to be merged?

2021-12-21 17:13 UTC, gAmUssA commented
@redsk testing... hang on

2021-12-23 18:45 UTC, gAmUssA commented
@redsk could you rebase with master (need to rename to main)? I want to test GH Actions integration. Thank you

2021-12-23 18:48 UTC, gAmUssA approved these changes

2021-12-28 15:02 UTC, redsk commented
@gAmUssA done

2022-01-05 14:03 UTC, redsk commented
@gAmUssA should I do something regarding the lint error about the version bump?

2022-01-10 18:21 UTC, gAmUssA commented
@redsk I need to figure out versioning schema and releasing automation. I will merge this. Thank you so much for your hard work.

2022-01-10 18:21 UTC, merged